server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'seth'
    password: 'password'
    url: jdbc:postgresql://localhost:5433/fraud

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true